### ISSUE TITLE
[Bug Report] Image is only built for linux/arm64?

### ISSUE THREAD

**Issue by cklingspor** [opencost/opencost-parquet-exporter#8]
Hi everyone,

as I was working on the helm chart for a PR I wanted to run in linux/arm64/v8 and encountered
`Failed to pull image "ghcr.io/opencost/opencost-parquet-exporter:latest": rpc error: code = Unknown desc = no matching manifest for linux/arm64/v8 in the manifest list entries` on my M1/minikube. 

I've take a look at the workflow and also checked the responsible action. Its docs point out the `platform` property: "Fixed [platforms](https://docs.docker.com/engine/reference/commandline/buildx_create/#platform) for current node. If not empty, values take priority over the detected ones.". It seems to me that we could extend the build with 
```

- name: Build and push Docker image with cache
        id: build-and-push
        if: github.event_name != 'schedule' &&  startsWith(github.ref, 'refs/tags/v') != true
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          ...
         platforms: linux/amd64, linux/arm64, linux/arm/v8, linux/arm/v7, linux/arm/v6
```
Specific values are debatable I guess. Same goes for the `build-and-push-nocache` block.

What do you think? Id raise the PR if you like :) 
All the best
Christoph
